version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./docker/mysql_data:/var/lib/mysql

  redis:
    image: redis:6.2-alpine
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./docker/redis_data:/data