# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Set up dependencies
      run: make dev-setup

    - name: Install dependencies
      run: make install

    # - name: Install swag
    #   run: go install github.com/swaggo/swag/cmd/swag@latest

    # - name: Create docs
    #   run: make swagger

    - name: Update go.sum
      run: make update-deps

    - name: Build with Makefile
      run: make build
